image: docker:git

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  - chmod +x -R ./scripts

.build_and_deploy_custom: &build_and_deploy_custom
  stage: build
  script:
    - ./scripts/custom-docker-build $CI_JOB_NAME -t "$CI_REGISTRY_IMAGE:$CI_JOB_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_JOB_NAME"
  only:
    - master

mongo-3.4.10: *build_and_deploy_custom
