FROM %CUSTOM_IMAGE_NAME%:%CUSTOM_IMAGE_VERSION%
MAINTAINER Hoang Nam "particle4dev@gmail.com"

COPY auth-docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN ln -s -f usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 27017
CMD ["mongod"]